bbatsov/clojure-style-guide

README.md

The first multi-arity example shows that an indented body is bad:
```clj
;; bad - extra indentation
(defn foo
"I have two arities."
([x]
(foo x 1))
([x y]
(+ x y)))
```
But the next example show an "okay" example with the same indentation style:
```clj
;; okay - the other arities are applications of the two-arity 
(defn foo
"I have two arities."
([x y]
(+ x y))
([x]
(foo x 1))
([x y z & more]
(reduce foo (foo x (foo y z)) more)))
```
I removed the extra indentation in the last example, which I think was related to tab characters sneaking into the file.

correct indentation in multi-arity examples

---

README.md

In my Clojure software archaeology corpus, I see no consistent evidence of the community preferring `..` for chaining interop forms.  I count 155 forms using `..` and 146 forms using `->` with interop.  The use of `..` seems to be a matter of individual taste and not of community style.

No evidence for preferring `..` to `->`.

---

README.md

Add section about test naming

---

README.md

The misplaced capitalization was causing a dead link.

typo `#Testing` => `#testing`

---

README.md

The syntax rule regarding usage of pos? and neg?
(https://github.com/bbatsov/clojure-style-guide#pos-and-neg) is not
applied within the example of the syntax rule regarding cond
(https://github.com/bbatsov/clojure-style-guide#else-keyword-in-cond).
This commit updates this example to be consistent with the pos? and neg?
rules.

Fix internal inconsistency regarding usage of pos? predicate

---

README.md

Hello!
Found out that "test-naming" rule layout was much different from other rules.
Other rules follow this pattern:
````
* <a name="rule-name"></a>
Rule text.
<sup>[[link](#rule-name)]</sup>
```clojure
(example)
```
````
It's not really a useful change but still:)

reorganize "test-naming" rule text to follow general rule template

---

README.adoc

Hi! Thanks for creating & maintaining this style guide! I was reading through and noticed a typo in the "Short Forms In Cond" section: https://guide.clojure.style/#shor-forms-in-cond
This PR fixes the typo in the displayed title and also fixes the same typo in the internal link.
Thanks again for maintaining this guide!

Fix "shor forms" typo

---

README.adoc

Currently, on GitHub, the conversion instructions are shown as `→`. However, the replacements also replace thread-last `->>` with `→>`, it does not seem human-readable.
I think it might be a good way to disable the replacements. It's also used in clojure.org .

Disable replacements of -> and ->>

---

README.adoc

As 'docstring' is a special domain entity, some consistency of spelling seems like it might be desirable.
Open to hearing counterarguments.
From the commit message:
The notion of a docstring currently occurs 22 times in the style guide.
This fixes the 5 non-standard spellings of ‘doc string’

Standardize docstring spelling

---

README.adoc

Currently it's a run-on sentence that is difficult to follow.
The proposed iteration is much shorter and easier to read while
maintaining a similar meaning.

Abbreviate 'Line Breaks in `ns`'

---

README.adoc

Fix language that is either unclear about its referent (inside what?) or awkwardly rendered (‘principle of the least surprise’)

Fix awkward language

---

README.adoc

This fixes two typos within the docstring grammar block and an error in
conventional usage of the word ‘comprise’.
It also arguably improves the flow of this section.

Docstring grammar typos and changes

---

README.adoc

This PR updates link to Japanese guide converted from Markdown to AsciiDoc.

Update link to Japanese guide

---

README.adoc

I think it is worth including the docstring recommendations from Cljdoc ([explained here](https://www.martinklepsch.org/posts/writing-awesome-docstrings.html)) and to encourage people to leverage Markdown for rich content.
Take this as a proposal and feel free to modify to fit better - or discuss.
Also, Contributing should link to GH.

Docstrings: use Markdown, [[links]]; link to GH

---

README.adoc

Just a typo in an example snippet.

Typo: curly brace should be parenthesis

---

README.adoc

Explicitly confirms, with an example, that the recommended style while using the threading macros is to line up the arguments.

confirms the lining up of arguments to threading macros

---

README.adoc

The quotes in the Docstring for the `Leverage Markdown in Docstrings` section need to be escaped. Otherwise the compiler will end the Docstring at the first encountered quote which is not what we want.

Escape quotes in Docstring example

---

README.adoc

The phrase "for currying" should be fixed.
The meaning of "currying" is actually different.
What we can do with [`partial`](https://clojuredocs.org/clojure.core/partial) is "partial application (of functions)".
Suppose there are functions like these:
```clojure
(defn add [x y] (+ x y))
(defn curried-add [x] (fn [y] (+ x y)))
(defn increment [y] (+ 1 y))
```
In the example above,
- "currying" is converting `add` to `curried-add`.
- "partial application" is converting `add` to `increment` (which means, fixing the value of `add`'s nth argument).

Fix description for `partial`

---

README.adoc

Here's my shot at describing `:no-doc`.  
Feedback most welcome.
Closes #221

Describe :no-doc metadata

---

README.adoc

The original "Use when instead of (if …​ (do …​))" made me skip it because I did not have a `do` in my code, only `(if cond something...)`. So I want to clarify that it applies to all single-branch ifs, no matter whether they use do or not.

when vs if clarification

---

README.adoc

"Has existed" is present perfect, while "was invented" is past
simple. If we remove "has," both become past simple tense.

Fix mix of present perfect and past tenses

---

README.adoc

alternatively the link could point to the book's page on Manning website:
https://www.manning.com/books/the-joy-of-clojure-second-edition

fixed broken link to The Joy of Clojure

---

README.adoc

Add the word 'gap,' where it was accidentally omitted.

Mind the gap

---

README.adoc

Reworded a sentence according to Sean Corfield's suggestion for the
bellow -> below fix.
gramatically -> grammatically

Fix codespell-detected issues: take 2

---

README.adoc

clojure.spec.alpha -> s
Show idiomatic by last segment, idiomatic by shorter alias, some third-party aliases.

proposal for #245

---

README.adoc

This PR adds two "Idiomatic Names" list entries, to cover `k` and `v` and their plurals. 
In my experience this is one of the most widespread name idioms in Clojure. Some of clojure.core uses the full "key" or "val", but `k`/`ks`/`v`/`vs` are used in many places, such as `dissoc`, `assoc-in`, `get-in`, `update`, `update-in`, and more. I see it frequently in library and project code as well.

Idiomatic names: k, v, ks, vs

---

README.adoc

I noticed the numbering of an ordered list wasn't rendering correctly, so I fixed it. I can see in [this commit](https://github.com/bbatsov/clojure-style-guide/commit/5fb64751a45b828f081948a75683b9ab6e7f0ec5) where you added the numbering to the document to try to fix it. That change could be reverted as well if you prefer to just use `.` for your ordered lists. Let me know if you'd like me to update this PR with that change as well.
Thanks for this great style guide, by the way! +1 for semantic formatting ☺️

Use list continuations to fix ordered list numbers
